Update learning.md
codefornola/nolabase pull request #2
Opened 2021-07-09 02:18 UTC by samanthasunne

wrote sql instructions

2021-07-09 17:48 UTC, nihonjinrxs requested changes
This is a great addition to the nolabase documentation! Thanks so much for your contribution here!

There are a few suggestions here. Most important is that it's important to put the string value in the `WHERE` clauses in single quotes. Other suggestions are for formatting that makes it easier to tell when something is a syntax statement within the prose.

2021-07-09 17:48 UTC, nihonjinrxs commented on docs/docs/learning.md
> +WHERE current_status = issued
Does this need quotes?
```suggestion
WHERE current_status = 'issued'
```

2021-07-09 17:48 UTC, nihonjinrxs commented on docs/docs/learning.md
> +"SELECT" tells the computer what data you want to see. In this case, we're asking to see the licensees' names. If you want to see all the columns at once, you can type an asterisk "*" to mean "all."
You can use the single back tick to set apart code keywords in monospace typeface, something like this:
```suggestion
`SELECT` tells the computer what data you want to see. In this case, we're asking to see the licensees' names. If you want to see all the columns at once, you can type an asterisk `*` to mean "all."
```
Similar for the ones below too.

2021-07-09 17:48 UTC, nihonjinrxs commented on docs/docs/learning.md
> +WHERE current_status = issued
```suggestion
WHERE current_status = 'issued'
```

2021-07-12 22:08 UTC, samanthasunne commented
Ok I think I added the ` to make the SQL commands stand out. Let me know if they don't show up

2021-07-20 20:36 UTC, mrcnc commented
@samanthasunne You can check the[ rendered version from your own branch](https://github.com/samanthasunne/nolabase/blob/patch-1/docs/docs/learning.md).  LGTM 👍

2021-07-28 19:30 UTC, samanthasunne commented
Thank you! It's still not appearing on
https://nolabase.codeforneworleans.org/docs/learning/

On Tue, Jul 20, 2021 at 1:37 PM Marc Cenac ***@***.***> wrote:

> @samanthasunne <https://github.com/samanthasunne> You can check the
> rendered version from your own branch
> <https://github.com/samanthasunne/nolabase/blob/patch-1/docs/docs/learning.md>.
> LGTM 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codefornola/nolabase/pull/2#issuecomment-883690052>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKRUWAKOYHHM42DLISU23LTYXM7BANCNFSM5AB3MKFQ>
> .
>

2021-10-15 00:13 UTC, nihonjinrxs approved these changes
Thanks for the updates!

2021-10-15 00:13 UTC, merged